services:
  video-stream:
    image: ghcr.io/110kanishkamedankara110/video-stream:latest
    container_name:  video-stream
    ports:
      - "8082:8080"
      - "4849:4848"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - glassfish_config:/glassfish/config
      - glassfish_logs:/glassfish/logs
      - root_dir_file_loc:/root/videoStream
    environment:
      - GLASSFISH_CONFIG_DIR=/glassfish/config
      - GLASSFISH_LOG_DIR=/glassfish/logs
  mysql_database:
    container_name: mysql_database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql_database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - mysql_database


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  glassfish_config:
  glassfish_logs:
  root_dir_file_loc:
